### ISSUE TITLE
use/support eslint_d

### ISSUE THREAD

**Issue by sonnyp** [roadhump/SublimeLinter-eslint#85]
See https://github.com/mantoni/eslint_d.js

**Comment by roadhump** [comment]
Here https://github.com/roadhump/SublimeLinter-eslint/releases/tag/1.7.0

Unfortunately it works only with saved files due to `eslint_d` limitations. I've created issue here https://github.com/mantoni/eslint_d.js/issues/2 and when it is fixed, it will be possible to make it works almost like `eslint` now.

**Comment by sonnyp** [comment]
Nice! thanks

**Comment by sonnyp** [comment]
with eslint_d local eslint is not being used when available not sure how to work around that

**Comment by roadhump** [comment]
Try to remove `eslint` installed by `eslint_d`, `rm -rf node_modules/eslint_d/node_modules/eslint`. I really don't know details how `npm` should resolve such dependencies now, since `peerDependencies` is derecated. Probably ask author of `eslint_d`, maybe `eslint` should be moved out of deps of `eslint_d` (or not).

**Comment by sonnyp** [comment]
cc @mantoni

**Comment by mantoni** [comment]
Wow, thanks for the fast integration work!

If you're using the new npm@3, you can specify a compatible eslint version in your package.json and only that one would be installed. A solution to make it use a globally installed eslint would be rather complicated because I'm using the eslint API and not just the binary. If you have any ideas, please open an issue for further discussions.

@roadhump I'm going to look into options now.
